"use sever"

import "./globals.css"; // Import global styles
import ClientLayout from "./layout.client"; // Import the client-side layout
import type { Metadata } from "next";


// Metadata for SEO and browser
export const metadata: Metadata = {
    title: "YouTube Clone",
    description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                {/* Wrap children with the client-side layout */}
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
}
